#!/usr/bin/env bash

echo "ffmpeg shim. input args: $FFMPEG_INPUT_ARGS, output args: $FFMPEG_OUTPUT_ARGS"

# shellcheck disable=SC2086
exec /usr/bin/ffmpeg $FFMPEG_INPUT_ARGS "$@" $FFMPEG_OUTPUT_ARGS
