#!/usr/bin/with-contenv bash
# shellcheck shell=bash

set -e

mounted() {
    mount | grep /recordings >/dev/null
}

CONFIG_DIR="${NEXTPVR_DATADIR_USERDATA%/}"

# Copy in scripts
for script in /nextpvr/custom_scripts/*; do
    dest="$CONFIG_DIR/scripts/$(basename "$script")"
    if [ -f "$dest" ]; then
        echo "Overwriting script $dest"
    fi
    cp "$script" "$dest"
done

# wait for mount
for _ in $(seq 60); do
    if mounted; then
        break
    fi
    echo "Waiting for mount..."
    sleep 1
done

if ! mounted; then
    echo "No recordings mount :/"
    exit 1
fi

mkdir -p "$CONFIG_DIR"
chown -R nextpvr:nextpvr "$CONFIG_DIR"
if [ -n "$RECORDED_DIR" ]; then
    chown -R nextpvr:nextpvr "$RECORDED_DIR"
fi

cd /nextpvr
PATH="/nextpvr/shims:$PATH" exec s6-setuidgid nextpvr \
    dotnet NextPVRServer.dll
