#!/usr/bin/with-contenv bash
# shellcheck shell=bash

set -e

mounted() {
    mount | grep /recordings >/dev/null
}

CONFIG_DIR="${NEXTPVR_DATADIR_USERDATA%/}"

# Copy in scripts
for script in /nextpvr/custom_scripts/*; do
    if ! [ -f "$CONFIG_DIR/scripts/$(basename "$script")" ]; then
        cp "$script" "$CONFIG_DIR/scripts/"
    else
        echo "$script already exists, skipping"
    fi  
done

# wait for mount
for _ in $(seq 60); do
    if mounted; then
        break
    fi
    echo "Waiting for mount..."
    sleep 1
done

if ! mounted; then
    echo "No recordings mount :/"
    exit 1
fi

mkdir -p "$CONFIG_DIR"
chown -R nextpvr:nextpvr "$CONFIG_DIR"
if [ -n "$RECORDED_DIR" ]; then
    chown -R nextpvr:nextpvr "$RECORDED_DIR"
fi

cd /nextpvr
exec s6-setuidgid nextpvr \
    dotnet NextPVRServer.dll
