#!/usr/bin/with-contenv bash
# shellcheck shell=bash

set -e

echo "I am $(whoami)"
umount /recordings || true
mkdir -p /recordings
chown -R nextpvr:nextpvr /recordings

exec s6-setuidgid nextpvr \
    rclone mount -v \
        --config="$RCLONE_CONFIG" \
        --cache-dir "${RCLONE_MOUNT_CACHE_DIR}" \
        --vfs-cache-mode full \
        --vfs-cache-poll-interval 1h0m0s \
        "$MOUNT_SOURCE" \
        /recordings
